### ISSUE TITLE
The braintree_ruby 3.4.x incompatibility with libxml-ruby 5.x

### ISSUE THREAD

**Issue by zorab47** [braintree/braintree_ruby#237]
### General information

* SDK/Library version: 3.4.0
* Environment: Sandbox and Production
* Language, language version, and OS: Ruby 3.1.4, MacOS Sonoma 14.2.1 (x86_64-darwin-23)

### Issue description

When upgrading `libxml-ruby` from 4.1.2 to 5.0.2 it the Braintree gem begins raising undefined method errors.

```ruby
      Failure/Error: result = Braintree::PaymentMethodNonce.find(nonce)
      
      NoMethodError:
        undefined method `default_keep_blanks=' for LibXML::XML:Module
```

See reference in https://github.com/braintree/braintree_ruby/blob/3.4.0/lib/braintree/xml/libxml.rb#L11.

It appears version 4.18.0 guards against the issue by using Rexml: https://github.com/braintree/braintree_ruby/blob/4.18.0/lib/braintree/xml/parser.rb#L23-L27.

**Comment by hollabaq86** [comment]
👋 thanks for reaching out, version 3.x of this SDK is [deprecated](https://developer.paypal.com/braintree/docs/reference/general/server-sdk-deprecation-policy#status-categories) and does not receive updates.

Do you encounter that same issue when using the latest version of this SDK, 4.18.0?

**Comment by zorab47** [comment]
No. Version 4.18.0 works with `libxml-ruby` 5.x. 👍

**Comment by hollabaq86** [comment]
Fantastic, closing this issue then.

On a more somber note, this will be my last comment for Braintree on Github. I was part of the group laid off this week. Hopefully I'll get to interact with folks in other open source libraries somewhere in the aether? Who knows.

If you discover this post in the future and are struggling to get help on an open issue, [contact Braintree Support](https://developer.paypal.com/braintree/help).

So long, and thanks for all the 🐟
